### ISSUE TITLE
Internal error when using topicctl with MSK IAM auth

### ISSUE THREAD

**Issue by ivan-santos-eq** [segmentio/topicctl#110]
Error:
```
time="2022-12-02 17:27:35" level=error msg="[58] SASL Authentication Failed: SASL Authentication failed: [d7cc65b2-8772-4b48-85f5-e97fdbc0b7a7]: Internal error"
```

cluster.yaml
```
meta:
  name: redacted
  environment: redacted
  region: redacted
  description: |
    redacted
spec:
  bootstrapAddrs:
  - "redacted:9098"

  tls:
    enabled: true
  sasl:
    enabled: true
    mechanism: AWS-MSK-IAM
```

From Cloudwatch:
```
Failed authentication with INTERNAL_IP/INTERNAL_IP ([redacted]: Internal error) (org.apache.kafka.common.network.Selector)
```

Not sure what that would be, but I got https://github.com/provectus/kafka-ui working with the same cluster.
