### ISSUE TITLE
Support for multiple yaml documents in topic config

### ISSUE THREAD

**Issue by mattrobenolt** [segmentio/topicctl#26]
It'd be nice to be able to apply a single say, `topics.yaml` file that was 1 file with the yaml document separator.

Such as (using the example data in the repo):

```yaml
meta:
  name: topic-default
  cluster: local-cluster
  environment: local-env
  region: local-region
  description: |
    Topic that uses default (any) strategy for assigning partition brokers.

spec:
  partitions: 3
  replicationFactor: 2
  retentionMinutes: 100
  placement:
    strategy: any
  settings:
    cleanup.policy: delete
    max.message.bytes: 5542880
---
meta:
  name: topic-static
  cluster: local-cluster
  environment: local-env
  region: local-region
  description: |
    Topic that uses static broker assignments.

spec:
  partitions: 10
  replicationFactor: 2
  retentionMinutes: 290
  placement:
    strategy: static
    staticAssignments:
      - [3, 4]
      - [5, 6]
      - [2, 1]
      - [2, 3]
      - [5, 1]
      - [2, 1]
      - [1, 3]
      - [2, 4]
      - [1, 3]
      - [2, 4]
---
meta:
  name: topic-in-rack
  cluster: local-cluster
  environment: local-env
  region: local-region
  description: |
    Topic that uses in-rack strategy for assigning brokers.

spec:
  partitions: 9
  replicationFactor: 2
  retentionMinutes: 100
  placement:
    strategy: in-rack
```
